# Generated by Django 5.1.1 on 2025-07-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeartPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('sex', models.IntegerField()),
                ('chest_pain_type', models.IntegerField()),
                ('resting_bp', models.IntegerField()),
                ('cholesterol', models.IntegerField()),
                ('fasting_bs', models.IntegerField()),
                ('resting_ecg', models.IntegerField()),
                ('max_hr', models.IntegerField()),
                ('exercise_angina', models.IntegerField()),
                ('oldpeak', models.FloatField()),
                ('st_slope', models.IntegerField()),
                ('prediction', models.IntegerField()),
                ('probability_0', models.FloatField()),
                ('probability_1', models.FloatField()),
                ('severity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
